GET http://localhost:8000/api/room_types


###
GET http://localhost:8000/api/room_type/4

###
POST http://localhost:8000/api/room_type?type='beta'


###
PUT http://localhost:8000/api/room_type/7?type='delta'

###
DELETE http://localhost:8000/api/room_type/7